-- DROP DATABASE IF EXISTS TemaBuy;
CREATE DATABASE IF NOT EXISTS TemaBuy;

USE TemaBuy;

CREATE TABLE IF NOT EXISTS users (
id BIGINT PRIMARY KEY,
nick VARCHAR(255) NOT NULL,
cash FLOAT NOT NULL DEFAULT 0,
access INT NOT NULL DEFAULT 0,
bought INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS product (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255),
price FLOAT NOT NULL,
tovar TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase (
id INT PRIMARY KEY AUTO_INCREMENT,
date_and_time_of_purchase DATETIME DEFAULT NOW(),
user_id BIGINT NOT NULL,
product_id INT NOT NULL,
FOREIGN KEY (product_id) REFERENCES product(id),
FOREIGN KEY (user_id) REFERENCES users(id)
);